### ISSUE TITLE
Squircle not recognizing correct size on initial render

### ISSUE THREAD

**Issue by janwirth** [bring-shrubbery/squircle-js#4]
I need to resize the browser window to fix this.

using NextJS

**Comment by bring-shrubbery** [comment]
Hey @janwirth 

Could you please provide a snippet of `jsx` and css you have around the place you have not working?

**Comment by bring-shrubbery** [comment]
Hmmm, I remember adding width/height overrides to the element, but somehow removed it in the end 🤔

I'll need to expose these props:

- `defaultWidth` - default width, but updates when size updates.
- `defaultHeight`- default height, but updates when size updates.
- `width` - overrides width, and disables resizing.
- `height` - overrides height, and disables resizing.

**Comment by bring-shrubbery** [comment]
@janwirth While I implement it back into the project, could you try setting the image `width` and `height` to the size that you expect it to take? This way the `Squircle` element should recognise the size of the content and calculate the correct size from the start.

**Comment by janwirth** [comment]
Hmm that's difficult because the image resizese dynamically based on the available space / it might also break into a new line.

**Comment by janwirth** [comment]
I will investigate the options though.

**Comment by bring-shrubbery** [comment]
Hmm, yes, I think having `aspectRatio` parameter would be extremely useful.

**Comment by bring-shrubbery** [comment]
Or maybe something like `recheckOnStateChage={state}` prop would solve this. But this would introduce an extra re-render on every state change, which is not something I'd like to just throw in the project for no reason.

**Comment by bring-shrubbery** [comment]
@janwirth I've published `@squircle-js/react@1.1.0` with the `width`, `height`, `defaultWidth`, `defaultHeight` and `asChild` props. Check if you can make it work with these props available. Also, I've added a couple of examples to the website, so feel free to check them out too.

**Comment by janwirth** [comment]
Thank you, sorry for not replying. I tried the updated version but I remember there were still some issues. However, we are not using this anymore. Thank you for your support.
